### ISSUE TITLE
tmpfile argument ignored

### ISSUE THREAD

**Issue by Brysonic** [ubc-library-rc/dryad2dataverse#20]
The --tmpfile argument currently has no effect. In the Transfer class in transfer.py, the download_files() function calls download_file, but doesn't pass in the tmp variable. It looks like the file list doesn't include that argument either.

Just wanted to also say that this project looks excellent! Thanks for all of your work on this so far!

**Comment by plesubc** [comment]
Thanks for pointing this out. Repaired in [v0.7.6](https://github.com/ubc-library-rc/dryad2dataverse/releases/tag/v0.7.6). As you can imagine we never used anything but /tmp.

The whole thing really needs refactoring but that can wait for another day.

**Comment by Brysonic** [comment]
That was fast! We're using it on Windows so the tmpfile thing became apparent fairly quickly.
