### ISSUE TITLE
Log location parameter being ignored

### ISSUE THREAD

**Issue by Brysonic** [ubc-library-rc/dryad2dataverse#21]
I just updated to 0.7.6 and it seems like the --log argument is now being ignored. I tried running the dryadd command on Windows with this argument: --log "C:\dryadd\dryadd.log" but I got the following error:
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\var\\log\\dryadd.log'

It looks like it's trying to use the default value. You can apparently count on me to be your dedicated argument parsing tester :-)

**Comment by plesubc** [comment]
I suspect that this is a Windows specific bug; I really need to upgrade the whole thing to use the more accessible `pathlib` library. I'll have a look as soon as I can, ideally tomorrow.

**Comment by plesubc** [comment]
One of my ideas was to have the configuration as a .toml file; is that something which appeals to you? It may simplify the lengthy command line specification.

**Comment by plesubc** [comment]
I just tried dryadd on Windows, and I'm unable to reproduce the problem, which is a bit odd.

Could you please supply the output of `dryadd --version`? (or dryadd.py)

As well, are you running `dryadd` from the command prompt (ie, cmd.exe), PowerShell, or bash (ie, Git Bash, cygwin, etc)?

Does the 'C:\dryadd\` directory already exist?

One potential cause of this could be how Windows handles strings and quotes in the shell environment, which varies depending on what you're using.  

You may have success by placing the file paths in double quotes (which I think you've done anyway). For example, 

`--log "C:\dryadd\dryadd.log"`.  But if you've already done that, then clearly that's not the issue.

**Comment by Brysonic** [comment]
Sorry for the confusion, I think this might have been my mistake. I used pip to update dryad2dataverse to 0.76 assuming that dryadd would also then be updated, but I just saw your note about the binary files lagging behind. This is my --version output:
`dryadd 0.6.3; dryad2dataverse 0.7.6`

I've been using the command prompt and C:\dryadd\ does exist. I'll try updating the binaries as that seems like the culprit.

**Comment by Brysonic** [comment]
As it turns out, the error I was getting was with an incorrect parameter - totally my fault. I had included --tmpfile "C:\dryadd\tmp\", but the last backslash escaped the quotation mark, so I think the parser ignored that argument as invalid. Removing that character got it working. 

Very sorry to have wasted your time on this, but thanks for looking into it! I'll close this issue.

**Comment by Brysonic** [comment]
Sorry, chose the wrong close option

**Comment by plesubc** [comment]
Thanks for letting me know; I will look into making this work a little better.
