### ISSUE TITLE
No email notification on expired/bad API key

### ISSUE THREAD

**Issue by plesubc** [ubc-library-rc/dryad2dataverse#4]
Dryad2dataverse fails on bad authentication. While that's added to the log, the log is not mailed to the dryadd recipients, so a manual check of the log is required. This is problematic because API keys expire yearly and probably no one keeps track of them until they stop working.

dryadd should email the key expiry note so that the correct parameter can be passed on the next run.

**Comment by eugene-barsky** [comment]
Put a note for myself for early April to renew the API key - thanks!

**Comment by plesubc** [comment]
Fixed in v0.4.0
