### ISSUE TITLE
Log email using Gmail fails with SMTP authentication error.

### ISSUE THREAD

**Issue by plesubc** [ubc-library-rc/dryad2dataverse#5]
Dryadd can crash if log messages are sent using Gmail.

Specifically, the application will crash on attempting to send an email with:

`smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepte
d. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials u1-20
020a1709026e0100b0015e8d4eb24fsm16002976plk.153 - gsmtp')`

Having a look at their documentation, there is this fun tidbit:

> To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password.

This means that emailing using just SMTPlib is not possible and alternate methods will be required to send email via gmail.

There are a number of possible solutions, none of which can be implemented in an afternoon.

<https://support.google.com/accounts/answer/6010255?hl=en&pli=1#zippy=%2Cif-less-secure-app-access-is-on-for-your-account%2Cupdate-your-app-or-operating-system%2Cuse-more-secure-apps%2Cuse-an-app-password>

Work on this can't commence for a few weeks: in the interim, don't use Google.

**Comment by eugene-barsky** [comment]
:(

**Comment by plesubc** [comment]
v0.5.0 now utilizes and SSL email handler for logging/notification.
